name: EC2 Launching using Terraform code
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write  
  contents: read   

jobs:
  deploy:
    name: Terraform Infra using EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        refs: use-case-2

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::173003893026:role/OIDC-github-actions
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7  # or your preferred version
        
    - name: Generate terraform docs
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        output-format: markdown table
        indention: 2
        git-push: true
        git-push-user-name: GitHub Actions
        git-push-user-email: actions@github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}


      
